"""Generate `wiki/timeline.md`: every dated event across the wiki, on one slider.

Per-page timelines answer "how did this topic get here". This answers "what happened, across
everything the wiki tracks" — the current state of affairs with a handle to drag backwards.

It needs no new UI: the page is a normal wiki page with a `## Timeline` section, so the site's
timeline component renders it exactly like any other. Regenerate it after a backfill or a nightly
run. No network or LLM calls.
"""

from __future__ import annotations

import argparse
import logging
import sys
from datetime import UTC, datetime
from pathlib import Path

try:
    from events import Event, EventKind
    from wiki_graph import WikiGraph, WikiGraphError, load_wiki_graph
except ModuleNotFoundError:  # Imported from outside research/scripts/.
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from events import Event, EventKind
    from wiki_graph import WikiGraph, WikiGraphError, load_wiki_graph

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(filename)s — %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = REPO_ROOT / "wiki" / "timeline.md"
# Keeps the page-attribution prefix out of the way of the bullet grammar's em-dash separator.
PAGE_SEPARATOR = " · "


def attributed_bullet(page_key: str, event: Event) -> str:
    """Render one event with a wikilink back to the page it belongs to.

    Args:
        page_key: Graph key of the owning page.
        event: The event.

    Returns:
        A bullet matching the standard timeline grammar.
    """
    prefixed = Event(
        date=event.date,
        event=f"[[{page_key}]]{PAGE_SEPARATOR}{event.event}",
        kind=event.kind,
        significance=event.significance,
        sources=event.sources,
        confidence=event.confidence,
    )
    return prefixed.to_bullet()


def render_page(graph: WikiGraph, events: list[tuple[str, Event]], generated_at: str) -> str:
    """Build the whole `wiki/timeline.md` body.

    Args:
        graph: Indexed wiki graph.
        events: (page key, event) pairs, oldest first.
        generated_at: Date recorded in the metadata block.

    Returns:
        The full markdown text of the page.
    """
    substantive = [pair for pair in events if pair[1].kind is not EventKind.WIKI]
    months = sorted({event.date.month_key for _, event in events})
    pages_covered = len({key for key, _ in events})

    lines = [
        "# Timeline",
        "",
        "> Every dated event the wiki tracks, on one axis — drag the slider to walk the whole field "
        "backwards instead of one topic at a time.",
        "",
        "**Category**: synthesis",
        f"**Last updated**: {generated_at}",
        "**Status**: active",
        "",
        "## What it is",
        "",
        f"A generated roll-up of the `## Timeline` section of every wiki page: {len(events)} events across "
        f"{pages_covered} pages, spanning {months[0]} to {months[-1]}. Each entry links back to the page that "
        "owns it, so the slider doubles as a way into whatever was happening in a given month.",
        "",
        f"Of those, {len(substantive)} are dated advances — papers, releases, methods, benchmarks — and the rest "
        "record when the wiki itself learned something.",
        "",
        "## Why it matters",
        "",
        "Per-page timelines answer how one topic got where it is. This one shows the shape of the field: where "
        "the dense months are, which threads moved together, and how far back the wiki's coverage actually "
        "reaches. Thin stretches are honest — they mark topics that have not been backfilled yet.",
        "",
        "## How it works",
        "",
        "Regenerated by `research/scripts/build_global_timeline.py`, which reads every page's Timeline section "
        "through the wiki graph and re-emits the events with a wikilink prefix. Nothing here is authored: fix a "
        "wrong event on its own page and regenerate.",
        "",
        "## Timeline",
        "",
        f"_Generated {generated_at} from {pages_covered} pages. Do not edit — fix the owning page and regenerate._",
        "",
    ]
    lines += [attributed_bullet(key, event) for key, event in events]
    lines += [
        "",
        "## Related",
        "",
        "- [[overview]]",
        "- [[technical/synthesis]]",
        "- [[world/synthesis]]",
        "",
    ]
    return "\n".join(lines)


def parse_args(argv: list[str]) -> argparse.Namespace:
    """Parse command-line arguments.

    Args:
        argv: Argument list without the program name.

    Returns:
        Parsed arguments namespace.
    """
    parser = argparse.ArgumentParser(description="Generate the wiki-wide timeline page.")
    parser.add_argument("--output", help=f"Where to write the page (default: {DEFAULT_OUTPUT.relative_to(REPO_ROOT)}).")
    parser.add_argument("--wiki-dir", help="Wiki root to index (default: the repo's wiki/).")
    parser.add_argument("--skip-wiki-events", action="store_true", help="Leave out wiki-kind bookkeeping events.")
    parser.add_argument("--dry-run", action="store_true", help="Print the page instead of writing it.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Generate the wiki-wide timeline page.

    Args:
        argv: Argument list without the program name; defaults to `sys.argv[1:]`.

    Returns:
        0 on success, 1 when the wiki cannot be indexed or the page cannot be written.
    """
    args = parse_args(sys.argv[1:] if argv is None else argv)
    output = Path(args.output) if args.output else DEFAULT_OUTPUT

    try:
        graph = load_wiki_graph(Path(args.wiki_dir) if args.wiki_dir else None)
    except WikiGraphError as error:
        logger.error("%s", error)
        return 1

    events = [pair for pair in graph.all_events() if output.stem != pair[0]]
    if args.skip_wiki_events:
        events = [pair for pair in events if pair[1].kind is not EventKind.WIKI]

    if not events:
        logger.error("No timeline events anywhere in the wiki — run seed_timelines.py first")
        return 1

    text = render_page(graph, events, datetime.now(UTC).strftime("%Y-%m-%d"))

    if args.dry_run:
        print(text)
        return 0

    try:
        output.write_text(text, encoding="utf-8")
    except OSError as error:
        logger.exception("Could not write %s", output)
        logger.error("%s", error)
        return 1

    months = sorted({event.date.month_key for _, event in events})
    logger.info(
        "Final summary: wrote %s with %d event(s) from %d page(s), %s → %s",
        output.relative_to(REPO_ROOT),
        len(events),
        len({key for key, _ in events}),
        months[0],
        months[-1],
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
